version: '3'

services:
  postgres:
    image: postgis/postgis
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - '5432:5432'
    volumes:
      - $PWD/pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: '${KEY}'
      PGADMIN_DEFAULT_PASSWORD: '${SECRET}'
    ports:
      - '5050:80'
    volumes:
      - $PWD/pgadmindata:/var/lib/pgadmin

  directus:
    image: directus/directus:9.24.0
    environment:
      KEY: '${KEY}'
      SECRET: '${SECRET}'
      ADMIN_EMAIL: '${ADMIN_EMAIL}'
      ADMIN_PASSWORD: '${ADMIN_PASSWORD}'
      DB_SSL__REJECT_UNAUTHORIZED: '${DB_SSL__REJECT_UNAUTHORIZED}'
      DB_CLIENT: '${DB_CLIENT}'
      DB_HOST: '${DB_HOST}'
      DB_PORT: '${DB_PORT}'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_SSL: '${DB_SSL}'
      CORS_ENABLED: "true"
      CORS_ORIGIN: "true"
    ports:
      - '8055:8055'
    depends_on:
      - postgres
    volumes:
      - $PWD/directusdata/database:/directus/database
      - $PWD/directusdata/extensions:/directus/extensions
      - $PWD/directusdata/uploads:/directus/uploads